"""add event categories and weekly energy budget

Revision ID: 56ea0a6d2672
Revises: 5cdc613d7ec2
Create Date: 2026-09-29 15:58:01.771281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56ea0a6d2672'
down_revision: Union[str, Sequence[str], None] = '5cdc613d7ec2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('category', sa.String(length=20), server_default='other', nullable=False))
    op.add_column('events', sa.Column('energy_cost_manual', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('users', sa.Column('weekly_energy_budget', sa.Integer(), server_default='100', nullable=False))
    op.drop_column('users', 'daily_energy_capacity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_energy_capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'weekly_energy_budget')
    op.drop_column('events', 'energy_cost_manual')
    op.drop_column('events', 'category')
    # ### end Alembic commands ###
